# A cloth manufacturing company is interested to know about the segment or attributes causes high sale. 


In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets  
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import  DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [2]:
# import data
companydata = pd.read_csv('Company_Data.Csv')

In [3]:
companydata.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [4]:
#Converting from categorical data
companydata['High'] = companydata.Sales.map(lambda x: 1 if x>8 else 0)
companydata['ShelveLoc']=companydata['ShelveLoc'].astype('category')
companydata['Urban']=companydata['Urban'].astype('category')
companydata['US']=companydata['US'].astype('category')
companydata.dtypes
companydata.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  High  
0         17   Yes  Yes     1  
1         10   Yes  Yes     1  
2         12   Yes  Yes     1  
3         14   Yes  Yes     0  
4         13   Yes   No     0

In [5]:
#label encoding to convert categorical values into numeric.
companydata['ShelveLoc']=companydata['ShelveLoc'].cat.codes
companydata['Urban']=companydata['Urban'].cat.codes
companydata['US']=companydata['US'].cat.codes
companydata.tail()

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
395  12.57        138     108           17         203    128          1   33   
396   6.14        139      23            3          37    120          2   55   
397   7.41        162      26           12         368    159          2   40   
398   5.94        100      79            7         284     95          0   50   
399   9.71        134      37            0          27    120          1   49   

     Education  Urban  US  High  
395         14      1   1     1  
396         11      0   1     0  
397         18      1   1     0  
398         12      1   1     0  
399         16      1   1     1

In [6]:
#Dependent and independent Variables
feature_cols=['CompPrice','Income','Advertising','Population','Price','ShelveLoc','Age','Education','Urban','US']
#x = company.drop(['Sales', 'High'], axis = 1)
x = companydata[feature_cols]
y = companydata.High
print(x)
print(y)

     CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0          138      73           11         276    120          0   42   
1          111      48           16         260     83          1   65   
2          113      35           10         269     80          2   59   
3          117     100            4         466     97          2   55   
4          141      64            3         340    128          0   38   
..         ...     ...          ...         ...    ...        ...  ...   
395        138     108           17         203    128          1   33   
396        139      23            3          37    120          2   55   
397        162      26           12         368    159          2   40   
398        100      79            7         284     95          0   50   
399        134      37            0          27    120          1   49   

     Education  Urban  US  
0           17      1   1  
1           10      1   1  
2           12      1   1  

In [7]:
#Train test Split
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2,random_state=0)

In [8]:
# fitting randomforest model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()



In [9]:
#model_1
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20,criterion='entropy', random_state=0,max_depth=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=20,
                       random_state=0)

In [10]:
y_pred = classifier.predict(x_test)

In [11]:
from sklearn.metrics import  classification_report, confusion_matrix
print('Classifcation report:\n', classification_report(y_test, y_pred))
conf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print('Confusion matrix:\n', conf_mat)

Classifcation report:
               precision    recall  f1-score   support

           0       0.72      0.91      0.80        43
           1       0.85      0.59      0.70        37

    accuracy                           0.76        80
   macro avg       0.78      0.75      0.75        80
weighted avg       0.78      0.76      0.76        80

Confusion matrix:
 [[39  4]
 [15 22]]


In [12]:
#model_2
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=30,criterion='entropy', random_state=0,max_depth=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=30,
                       random_state=0)

In [13]:
y_pred_2 = classifier.predict(x_test)

In [14]:
from sklearn.metrics import  classification_report, confusion_matrix
print('Classifcation report:\n', classification_report(y_test, y_pred_2))
conf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred_2)
print('Confusion matrix:\n', conf_mat)

Classifcation report:
               precision    recall  f1-score   support

           0       0.72      0.88      0.79        43
           1       0.81      0.59      0.69        37

    accuracy                           0.75        80
   macro avg       0.77      0.74      0.74        80
weighted avg       0.76      0.75      0.74        80

Confusion matrix:
 [[38  5]
 [15 22]]


# A cloth manufacturing company is interested to know about the segment or attributes causes high sale. 


In [15]:
fraud=pd.read_csv('C:\\Users\\acer\\Documents\\Excel r\\Assignments\\Decision Tree\\Fraud_check.csv')

In [16]:
##Converting the Taxable income variable to bucketing. 
fraud["income"]="<=30000"
fraud.loc[fraud["Taxable.Income"]>=30000,"income"]="Good"
fraud.loc[fraud["Taxable.Income"]<=30000,"income"]="Risky"


In [17]:
##Droping the Taxable income variable
fraud.drop(["Taxable.Income"],axis=1,inplace=True)
fraud.rename(columns={"Undergrad":"undergrad","Marital.Status":"marital","City.Population":"population","Work.Experience":"experience","Urban":"urban"},inplace=True)


In [18]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for column_name in fraud.columns:
    if fraud[column_name].dtype == object:
        fraud[column_name] = le.fit_transform(fraud[column_name])
    else:
        pass


In [19]:
##Splitting the data into featuers and labels
features = fraud.iloc[:,0:5]
labels = fraud.iloc[:,5]



In [20]:
## Collecting the column names
colnames = list(fraud.columns)
predictors = colnames[0:5]
target = colnames[5]


In [21]:
##Splitting the data into train and test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size = 0.2,stratify = labels)



In [22]:
# fitting randomforest model
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()



In [23]:
#model_1
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=20,criterion='entropy', random_state=0,max_depth=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=20,
                       random_state=0)

In [24]:
y_pred = classifier.predict(x_test)

In [26]:
from sklearn.metrics import  classification_report, confusion_matrix
print('Classifcation report:\n', classification_report(y_test, y_pred))
conf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print('Confusion matrix:\n', conf_mat)

Classifcation report:
               precision    recall  f1-score   support

           0       0.79      0.95      0.86        95
           1       0.17      0.04      0.06        25

    accuracy                           0.76       120
   macro avg       0.48      0.49      0.46       120
weighted avg       0.66      0.76      0.70       120

Confusion matrix:
 [[90  5]
 [24  1]]
